name: cd

on:
  push:
    branches: [main]

jobs:
  style:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Build
        run: ./scripts/buildprod.sh
      - name: Migrations
        run: ./scripts/migrateup.sh
      - name: GCP Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Build and Deploy"
        run: gcloud builds submit --tag us-east5-docker.pkg.dev/notely-418314/notely-ar-repo/notely:lastest .
